FROM jupyter/scipy-notebook:d4cbf2f80a2a
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8


USER root


RUN apt-get update --fix-missing && apt-get install -y \
    byobu \
    ca-certificates \
    curl \
    git-core \
    htop \
    unzip \
    wget \
    libpq-dev \
    python-dev \
    python3-dev \
    build-essential \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


ENV PATH /opt/conda/bin:$PATH



RUN conda install tensorflow -y


RUN pip install --upgrade pip

RUN pip --no-cache-dir install \
    boto3 \
    awscli --ignore-installed PyYAML \
    jupyter \
    jupyterlab \
    keras \
    numpy \
    pandas \
    psycopg2-binary \
    sqlalchemy \
    sqlalchemy_redshift

# seems 2 versions of numpy are installed. This is a fix
RUN pip uninstall -y numpy; pip uninstall -y numpy;pip uninstall -y numpy

# add this to install local packages in docker image
#RUN mkdir /shared_utils # create a file
#COPY docker/ds-utils /shared_utils/ # copy package into docker
#RUN cd /shared_utils; python setup.py install; # install

USER jovyan
WORKDIR /home/jovyan/
# if rebulding notebook need to delete old config
RUN rm -rf /home/jovyan/.jupyter

RUN jupyter notebook --generate-config
CMD jupyter lab --allow-root --ip=0.0.0.0
