name: zindi_farmpin
channels:
  - anaconda
  - conda-forge
  - defaults
  - menpo
dependencies:
  - pip
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - python=3.7
  - scikit-learn
  - seaborn
  - opencv
  - pip:
      - keras
      - tensorflow
      - xgboost
      - sklearn
      - geopandas
      - rasterio
