name: zindi_farmpin
channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - pip
  - pillow
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pandas-profiling
  - path.py
  - python=3.7
  - scikit-learn
  - seaborn
  - statsmodels
#  - pytorch torchvision cudatoolkit=9.0
  - pip:
      - h2o
      - kaggle
      - keras
      - lightgbm
      - missingno
      - nbdime
      - plotly
      - pylint
      - pyspark
      - tensorflow-gpu
      - xgboost
      - sklearn
      - geopandas
      - rasterio
